---
environment_variables:
  NEXTCLOUD_VERSION: "32.0.0rc3"
git:
  branch: upstream_master
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_name: drive/nextcloud-base
docker_tags:
  - "${NEXTCLOUD_VERSION}"
  - "latest"
docker_no_cache: true
